openapi: 3.0.0
swaggerDefinition:
  info:
    description: Something about the API
    version: 1.0.0
    title: Test API
  servers:
    - url: /api/v1
  paths:
    /login:
      post:
        tags:
          - 帳號
        summary: 登入
        consumes:
          - application/json
        parameters:
          - in: body
            name: user
            description: 帳號密碼
            schema:
              "$ref": "#/components/schemas/AccountInfo"
        responses:
          200:
            description: 登入
  components:
    schemas:
      AccountInfo:
        type: object
        properties:
          name:
            type: string
            format: string
          psw: 
            type: string
            format: string
apis: ["./routes/*.js"]