openapi: 3.0.0
swaggerDefinition:
  info:
    description: API
    version: 1.0.1
    title: Swagger API Docs
  paths:
    # /login:
    #   post:
    #     tags:
    #       - 帳號
    #     summary: 登入
    #     consumes:
    #       - application/json
    #     parameters:
    #       - in: body
    #         name: user
    #         description: 帳號密碼
    #         schema:
    #           "$ref": "#/components/schemas/AccountInfo"
    #     responses:
    #       200:
    #         description: 登入
    /queryTodayMsgRecord:
      get:
        tags:
          - 留言訊息
        description: 撈今天收到的訊息
        responses:
          '200':
            description: A successful response
    /queryAllMsgRecord:
      get:
        tags:
          - 留言訊息
        description: 撈今天收到的訊息
        responses:
          '200':
            description: A successful response
    /broadcastAll:
      post:
        tags:
          - 訊息推播
        description: 官方line頻道訊息
        consumes:
          - application/json
        parameters:
          - in: body
            name: 內容
            description: 推送內容
            schema:
              "$ref": "#/components/schemas/MsgPush"
        response:
          '200':
            description: A successful response
  components:
    schemas:
      # AccountInfo:
      #   type: object
      #   properties:
      #     name:
      #       type: string
      #       format: string
      #     psw: 
      #       type: string
      #       format: string
      MsgPush:
        type: object
        properties:
          msg:
            type: string
            format: string
apis: ["./routes/*.js"]