openapi: 3.0.0
swaggerDefinition:
  info:
    description: API
    version: 1.0.1
    title: Swagger API Docs
  paths:
    /msgRecords:
      get:
        tags:
          - 留言訊息
        description: 撈今天收到的訊息
        responses:
          '200':
            description: A successful response
          '301':
            description: brocast fail
    /msgRecords/today:
      get:
        tags:
          - 留言訊息
        description: 撈今天收到的訊息
        responses:
          '200':
            description: A successful response
    /broadcast:
      get:
        tags: 
          - 訊息推播
        description: 官方line頻道訊息  
        responses:
          '200':
            description: A successful response
      post:
        tags:
          - 訊息推播
        description: 官方line頻道訊息
        consumes:
          - application/json
        parameters:
          - in: body
            name: 內容
            description: 推送內容。img欄位為圖片檔名，需要先透過post /upload後才可以推送成功
            schema:
              "$ref": "#/components/schemas/MsgPush"
        response:
          '200':
            description: A successful response
    /upload:
      post:
        tags: 
          - 推播圖片
        consumes:
          - multipart/form-data
        parameters:
          - name: file
            in: formData  
            description: The uploaded file data
            required: true
            type: file
        response:
          '200':
            description: 上傳成功
    /upload/{image}: 
      get:
        tags:
          - 推播圖片
        parameters:
          - name: image
            in: path
            description: image name
            required: true
            type: string
            schema: 
              type: string
              format: string
        responses:
          '200':
            description: image OK!
            content:
              image/png:
                schema:
                  type: string
                  format: binary
  components:
    schemas:
      MsgPush:
        type: object
        properties:
          msg:
            type: string
            format: string
          img:
            type: string
            format: string
apis: ["./routes/*.js"]